---
# =============================================================================
# Zsh with Oh-My-Zsh Installation Role
# =============================================================================
# Installs zsh, oh-my-zsh, autosuggestions, and syntax highlighting plugins

- name: Install zsh package
  apt:
    name: zsh
    state: present
    update_cache: true

- name: Check if oh-my-zsh is already installed
  stat:
    path: /home/{{ gastown_user }}/.oh-my-zsh
  register: ohmyzsh_installed

- name: Download oh-my-zsh install script
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh-install.sh
    mode: '0755'
  when: not ohmyzsh_installed.stat.exists

- name: Install oh-my-zsh for gastown user
  become: true
  become_user: "{{ gastown_user }}"
  shell: sh /tmp/ohmyzsh-install.sh --unattended
  args:
    creates: /home/{{ gastown_user }}/.oh-my-zsh
  when: not ohmyzsh_installed.stat.exists

- name: Remove oh-my-zsh install script
  file:
    path: /tmp/ohmyzsh-install.sh
    state: absent

- name: Clone zsh-autosuggestions plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: /home/{{ gastown_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1
  become: true
  become_user: "{{ gastown_user }}"

- name: Clone zsh-syntax-highlighting plugin
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /home/{{ gastown_user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    depth: 1
  become: true
  become_user: "{{ gastown_user }}"

- name: Deploy .zshrc configuration
  template:
    src: .zshrc.j2
    dest: /home/{{ gastown_user }}/.zshrc
    owner: "{{ gastown_user }}"
    group: "{{ gastown_user }}"
    mode: '0644'

- name: Change default shell to zsh for gastown user
  user:
    name: "{{ gastown_user }}"
    shell: /usr/bin/zsh

- name: Display zsh installation complete
  debug:
    msg:
      - "=========================================="
      - "Zsh + Oh-My-Zsh Installation Complete"
      - "=========================================="
      - "User: {{ gastown_user }}"
      - "Theme: robbyrussell"
      - "Plugins: git, docker, zsh-autosuggestions, zsh-syntax-highlighting"
      - "=========================================="
