---
- name: Install tmux
  apt:
    name: tmux
    state: present

- name: Deploy tmux configuration with scrollback
  template:
    src: tmux.conf.j2
    dest: /etc/tmux.conf
    owner: root
    group: root
    mode: '0644'
