---
- name: Install beads CLI via Go
  become_user: "{{ roughneck_user }}"
  shell: |
    export PATH="/usr/local/go/bin:$HOME/go/bin:$PATH"
    go install github.com/steveyegge/beads/cmd/bd@latest
  args:
    creates: "/home/{{ roughneck_user }}/go/bin/bd"
